services:
  db:
    image: postgres:18-bookworm
    container_name: postgres18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pandoc:
    image: pandoc/typst:latest
    container_name: pandoc-typst
    working_dir: /data
    volumes:
      - ./docs:/data
    entrypoint: ["sleep", "infinity"]

volumes:
  pgdata:

